// Frame values are expressed in simulation ticks (fixed timestep, 60 ticks/sec).
// All characters, attacks and stats are original creations for ARENA PULSE.

export const CHARACTERS = [
  {
    id: 'varkan',
    name: 'VARKAN',
    title: 'DER GEFALLENE WÄCHTER',
    description: 'Ein ehemaliger Arenakrieger in schwerer Rüstung. Langsam, aber verheerend im Nahkampf.',
    color: { primary: '#7a1f1f', secondary: '#2b2624', accent: '#ffb347' },
    stats: { power: 9, speed: 3, defense: 8 },
    health: 1150,
    walkSpeed: 3.4,
    dashSpeed: 6.5,
    jumpPower: -16.5,
    build: { width: 82, height: 168, headR: 20 },
    specialName: 'SIEGEBREAKER',
    specialDescription: 'Ein gepanzerter Vorstoß, der den Gegner mit einem einzigen wuchtigen Schlag zu Boden reißt.',
    attacks: {
      light: { name: 'Kettenhieb', damage: 8, startup: 6, active: 4, recovery: 12, knockback: 3, hitstun: 12, blockstun: 8, energyGain: 8, range: 78, width: 56, height: 40 },
      heavy: { name: 'Rammschlag', damage: 20, startup: 14, active: 5, recovery: 24, knockback: 9, hitstun: 20, blockstun: 12, energyGain: 12, range: 92, width: 66, height: 50 },
      special: { name: 'Siegebreaker', damage: 34, startup: 16, active: 8, recovery: 26, knockback: 14, hitstun: 26, blockstun: 16, energyGain: 0, range: 110, width: 90, height: 70 },
      grab: { name: 'Eiserner Griff', damage: 18, startup: 9, active: 3, recovery: 22, knockback: 16, hitstun: 24, blockstun: 0, energyGain: 10, range: 58, width: 44, height: 60 },
    },
  },
  {
    id: 'nyra',
    name: 'NYRA',
    title: 'DIE SCHATTENKLINGE',
    description: 'Eine extrem schnelle Schattenkämpferin mit tödlichen Combos, aber dünner Deckung.',
    color: { primary: '#2b2b3a', secondary: '#151018', accent: '#7fd8ff' },
    stats: { power: 5, speed: 10, defense: 4 },
    health: 850,
    walkSpeed: 5.6,
    dashSpeed: 10.5,
    jumpPower: -18.5,
    build: { width: 58, height: 150, headR: 16 },
    specialName: 'SCHATTENSCHNITT',
    specialDescription: 'Eine blitzschnelle Serie von Klingenhieben aus der Dunkelheit heraus.',
    attacks: {
      light: { name: 'Nadelstich', damage: 6, startup: 3, active: 3, recovery: 7, knockback: 1, hitstun: 9, blockstun: 6, energyGain: 7, range: 62, width: 46, height: 34 },
      heavy: { name: 'Sichelschlag', damage: 15, startup: 9, active: 4, recovery: 16, knockback: 6, hitstun: 16, blockstun: 10, energyGain: 10, range: 74, width: 56, height: 40 },
      special: { name: 'Schattenschnitt', damage: 30, startup: 10, active: 10, recovery: 20, knockback: 8, hitstun: 24, blockstun: 14, energyGain: 0, range: 100, width: 84, height: 56, multiHit: 3 },
      grab: { name: 'Schattengriff', damage: 14, startup: 7, active: 3, recovery: 18, knockback: 14, hitstun: 22, blockstun: 0, energyGain: 9, range: 52, width: 40, height: 54 },
    },
  },
  {
    id: 'kael',
    name: 'KAEL',
    title: 'DER ENERGIEKRIEGER',
    description: 'Ein kontrollierter Kämpfer, der Energieprojektile aus mittlerer Distanz einsetzt.',
    color: { primary: '#1f4a5c', secondary: '#101a20', accent: '#ffcf6b' },
    stats: { power: 6, speed: 6, defense: 6 },
    health: 950,
    walkSpeed: 4.4,
    dashSpeed: 8.2,
    jumpPower: -17.2,
    build: { width: 66, height: 158, headR: 18 },
    specialName: 'ENERGIEWELLE',
    specialDescription: 'Ein gebündelter Energieblitz, der über die gesamte Arena hinweg trifft.',
    attacks: {
      light: { name: 'Energiestoß', damage: 7, startup: 5, active: 3, recovery: 10, knockback: 2, hitstun: 10, blockstun: 7, energyGain: 8, range: 70, width: 50, height: 38 },
      heavy: { name: 'Flammenbogen', damage: 17, startup: 11, active: 5, recovery: 20, knockback: 7, hitstun: 18, blockstun: 11, energyGain: 11, range: 84, width: 60, height: 46 },
      special: { name: 'Energiewelle', damage: 26, startup: 14, active: 6, recovery: 18, knockback: 10, hitstun: 22, blockstun: 14, energyGain: 0, range: 999, width: 36, height: 30, projectile: true, projectileSpeed: 13 },
      grab: { name: 'Kraftgriff', damage: 16, startup: 8, active: 3, recovery: 20, knockback: 15, hitstun: 22, blockstun: 0, energyGain: 9, range: 55, width: 42, height: 56 },
    },
  },
  {
    id: 'morvan',
    name: 'MORVAN',
    title: 'DER BERSERKER',
    description: 'Ein brutaler Nahkämpfer mit enormem Risiko und noch größerer Angriffskraft.',
    color: { primary: '#5c1414', secondary: '#1c1010', accent: '#ff6b3d' },
    stats: { power: 10, speed: 5, defense: 5 },
    health: 1000,
    walkSpeed: 4.8,
    dashSpeed: 9.0,
    jumpPower: -17.8,
    build: { width: 74, height: 162, headR: 19 },
    specialName: 'BLUTRAUSCH',
    specialDescription: 'Eine unaufhaltsame Angriffsserie, die jeden Treffer in massiven Schaden verwandelt.',
    attacks: {
      light: { name: 'Faustschlag', damage: 9, startup: 5, active: 3, recovery: 11, knockback: 3, hitstun: 11, blockstun: 7, energyGain: 8, range: 66, width: 52, height: 38 },
      heavy: { name: 'Wutschwinger', damage: 23, startup: 13, active: 5, recovery: 23, knockback: 10, hitstun: 20, blockstun: 12, energyGain: 12, range: 80, width: 64, height: 48 },
      special: { name: 'Blutrausch', damage: 38, startup: 12, active: 12, recovery: 22, knockback: 12, hitstun: 28, blockstun: 16, energyGain: 0, range: 90, width: 78, height: 60, multiHit: 4 },
      grab: { name: 'Zermalmer', damage: 20, startup: 8, active: 3, recovery: 21, knockback: 17, hitstun: 25, blockstun: 0, energyGain: 10, range: 56, width: 46, height: 58 },
    },
  },
  {
    id: 'ninja',
    name: 'KAGE',
    title: 'DIE SCHATTENKLINGE DES KAGE-CLANS',
    description: 'Ein lautloser Attentäter mit Katana, der aus der Dunkelheit zuschlägt und wieder verschwindet.',
    color: { primary: '#141210', secondary: '#0c0a08', accent: '#d4a24a' },
    stats: { power: 6, speed: 9, defense: 5 },
    health: 900,
    walkSpeed: 5.2,
    dashSpeed: 9.8,
    jumpPower: -18.0,
    build: { width: 68, height: 160, headR: 17 },
    specialName: 'SCHATTENSCHNITT',
    specialDescription: 'Ein blitzschneller Katana-Wirbel, der den Gegner in einer Serie tödlicher Schnitte erfasst.',
    model3d: 'models/ninja.glb',
    rigKind: 'ninja',
    attacks: {
      light: { name: 'Klingenstich', damage: 7, startup: 4, active: 3, recovery: 8, knockback: 2, hitstun: 10, blockstun: 7, energyGain: 8, range: 68, width: 50, height: 36 },
      heavy: { name: 'Fallender Schnitt', damage: 18, startup: 10, active: 4, recovery: 18, knockback: 7, hitstun: 18, blockstun: 11, energyGain: 11, range: 80, width: 60, height: 44 },
      special: { name: 'Schattenschnitt', damage: 32, startup: 11, active: 10, recovery: 21, knockback: 9, hitstun: 25, blockstun: 15, energyGain: 0, range: 96, width: 82, height: 56, multiHit: 3 },
      grab: { name: 'Todesgriff', damage: 15, startup: 7, active: 3, recovery: 19, knockback: 14, hitstun: 22, blockstun: 0, energyGain: 9, range: 54, width: 42, height: 54 },
    },
  },
  {
    id: 'cassius',
    name: 'CASSIUS',
    title: 'DER VERBANNTE HAUPTMANN',
    description: 'Ein disziplinierter Ex-Offizier, aus der Armee verbannt. Kämpft mit gepanzerten Fäusten und eiserner Deckung.',
    color: { primary: '#3a5a8c', secondary: '#1f2e42', accent: '#e0932e' },
    stats: { power: 7, speed: 5, defense: 8 },
    health: 1050,
    walkSpeed: 4.6,
    dashSpeed: 8.8,
    jumpPower: -17.5,
    build: { width: 70, height: 162, headR: 18 },
    specialName: 'LETZTER BEFEHL',
    specialDescription: 'Ein disziplinierter Sturmangriff, der jede gegnerische Deckung durchbricht.',
    model3d: 'models/cassius.glb',
    rigKind: 'skeletal',
    attacks: {
      light: { name: 'Gepanzerter Schlag', damage: 8, startup: 6, active: 3, recovery: 11, knockback: 3, hitstun: 11, blockstun: 7, energyGain: 8, range: 72, width: 54, height: 38 },
      heavy: { name: 'Rammstoß', damage: 19, startup: 12, active: 5, recovery: 21, knockback: 8, hitstun: 19, blockstun: 12, energyGain: 11, range: 84, width: 62, height: 46 },
      special: { name: 'Letzter Befehl', damage: 31, startup: 13, active: 7, recovery: 22, knockback: 11, hitstun: 24, blockstun: 15, energyGain: 0, range: 92, width: 76, height: 54 },
      grab: { name: 'Hauptmannsgriff', damage: 16, startup: 8, active: 3, recovery: 20, knockback: 15, hitstun: 22, blockstun: 0, energyGain: 9, range: 55, width: 44, height: 56 },
    },
  },
  {
    id: 'brannok',
    name: 'BRANNOK',
    title: 'DER EISERNE WÄCHTER',
    description: 'Ein wandelnder Rüstungsturm. Was ihm an Tempo fehlt, macht er mit roher Wucht und unerschütterlicher Deckung wett.',
    color: { primary: '#8c2a2a', secondary: '#2b1414', accent: '#e0a838' },
    stats: { power: 9, speed: 2, defense: 10 },
    health: 1300,
    walkSpeed: 3.0,
    dashSpeed: 6.2,
    jumpPower: -16.0,
    build: { width: 78, height: 172, headR: 20 },
    specialName: 'ERDBEBENSCHLAG',
    specialDescription: 'Ein gewaltiger Schlag auf den Boden, der die gesamte Arena erzittern lässt.',
    model3d: 'models/brannok.glb',
    rigKind: 'skeletal',
    attacks: {
      light: { name: 'Kettenfaust', damage: 9, startup: 8, active: 4, recovery: 14, knockback: 4, hitstun: 13, blockstun: 8, energyGain: 8, range: 76, width: 58, height: 42 },
      heavy: { name: 'Turmschlag', damage: 24, startup: 16, active: 6, recovery: 26, knockback: 11, hitstun: 22, blockstun: 13, energyGain: 13, range: 88, width: 68, height: 50 },
      special: { name: 'Erdbebenschlag', damage: 36, startup: 18, active: 8, recovery: 26, knockback: 15, hitstun: 28, blockstun: 17, energyGain: 0, range: 100, width: 90, height: 60 },
      grab: { name: 'Zermalmende Umarmung', damage: 21, startup: 9, active: 3, recovery: 23, knockback: 18, hitstun: 26, blockstun: 0, energyGain: 10, range: 58, width: 48, height: 60 },
    },
  },
  {
    id: 'solkan',
    name: 'SOLKAN',
    title: 'DER KNOCHENBOGEN',
    description: 'Ein untoter Bogenschütze, gebunden an die Arena durch einen uralten Fluch. Trifft aus der Distanz, bevor der Gegner ihn überhaupt sieht.',
    color: { primary: '#c9c2ab', secondary: '#4a4034', accent: '#7fd858' },
    stats: { power: 4, speed: 7, defense: 3 },
    health: 780,
    walkSpeed: 4.9,
    dashSpeed: 9.2,
    jumpPower: -17.6,
    build: { width: 62, height: 158, headR: 16 },
    specialName: 'KNOCHENPFEIL',
    specialDescription: 'Ein verfluchter Pfeil aus splitterndem Knochen, der über die gesamte Arena hinweg trifft.',
    model3d: 'models/solkan.glb',
    rigKind: 'skeletal',
    attacks: {
      light: { name: 'Knöcherner Stich', damage: 6, startup: 4, active: 3, recovery: 8, knockback: 2, hitstun: 9, blockstun: 6, energyGain: 7, range: 64, width: 46, height: 34 },
      heavy: { name: 'Knüppelschwung', damage: 15, startup: 9, active: 4, recovery: 17, knockback: 6, hitstun: 16, blockstun: 10, energyGain: 10, range: 76, width: 56, height: 40 },
      special: { name: 'Knochenpfeil', damage: 27, startup: 14, active: 6, recovery: 19, knockback: 9, hitstun: 22, blockstun: 13, energyGain: 0, range: 999, width: 34, height: 28, projectile: true, projectileSpeed: 15 },
      grab: { name: 'Klapperngriff', damage: 13, startup: 7, active: 3, recovery: 18, knockback: 13, hitstun: 21, blockstun: 0, energyGain: 8, range: 50, width: 38, height: 52 },
    },
  },
];

export function getCharacter(id) {
  return CHARACTERS.find((c) => c.id === id) || CHARACTERS[0];
}
